management:
   security:
      enabled: false
machinelearningops:
   userName: 3BFC70SQO7IWMS7GZUAU
   paswrd: zmJ4e+mt+ywIpDLNX2m9OPGE4d63ZTcKWgR7ZhkR
   url: "https://[240b:c0e0:0104:544d:b462:2::]:30000"
   bucketName: mlops-api
   scriptFolderPath: script
   dataFolderPath: data
   modelFolderPath: model

sample-files:
  dataSamplePath: /opt/app/data_sample1.zip
  codeSamplePath: /opt/app/code_sample1.zip

ml-ops:
  scriptPath: /mlops/scripts/

cron.expression: 0 11 07 * * WED
server.port: 8888
    
spring:
   sql.init.mode: ALWAYS
   sql.init.continue-on-error: true
   servlet.multipart.max-file-size: -1
   servlet.multipart.max-request-size: -1
   jpa:
      defer-datasource-initialization: true
      database-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate:
         ddl-auto: update
   datasource:
      generate-ddl: true
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://katib-mysql:3306/mlopstest2?createDatabaseIfNotExist=true&characterEncoding=utf8&enabledTLSProtocols=TLSv1.2&useSSL=false
      username: root
      password: test
      #username: user
      #password: P@ssW0rd
      show-sql: true