management:
   security:
      enabled: false
machinelearningops:
   userName: 9B624T1B5KJX85F5LBBO
   paswrd: 3ON29QhCcpDIZ0yB1uwAEcGFDjWaj7awNxIiL4k+
   url: "https://[240b:c0e0:102:5dda:b422:2::]:30000"
   bucketName: mlops-api
   scriptFolderPath: script
   dataFolderPath: data
   modelFolderPath: model

sample-files:
  dataSamplePath: /opt/app/data_sample1.zip
  codeSamplePath: /opt/app/code_sample1.zip

ml-ops:
  scriptPath: /mlops/scripts/

cron.expression: 0 11 07 * * WED
server.port: 8888
    
spring:
   sql.init.mode: ALWAYS
   //sql.init.continue-on-error: true
   servlet.multipart.max-file-size: -1
   servlet.multipart.max-request-size: -1
   jpa:
      defer-datasource-initialization: true
      database-platform: org.hibernate.dialect.MySQL57Dialect
      hibernate:
         ddl-auto: update
   datasource:
      generate-ddl: true
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://mysql:3306/mlops?createDatabaseIfNotExist=true&characterEncoding=utf8&enabledTLSProtocols=TLSv1.2&useSSL=false
      username: root
      password: 
      #username: user
      #password: P@ssW0rd
      show-sql: true